- hosts: all
  remote_user: dietpi
  become: true

  tasks:
  - name: Copy pycar directory
    copy:
      src: ../pycar
      dest: /home/dietpi/pycar/pycar
      owner: dietpi
      group: dietpi
      force: yes

  - name: Copy requirements.txt
    copy:
      src: ../requirements.txt
      dest: /home/dietpi/pycar/requirements.txt
      owner: dietpi
      group: dietpi
      force: yes

  - name: Install python virtualenv packages
    pip:
      virtualenv: /home/dietpi/pycar/venv
      virtualenv_site_packages: yes
      requirements: /home/dietpi/pycar/requirements.txt